### ISSUE TITLE
New Relic stopped supporting TLS 1.0

### ISSUE THREAD

**Issue by noamgrinch** [nomansadiq11/newrelic-deployment-marker#2]
When trying to use this task(script) an error message is shown:
**The request was aborted: Could not create SSL/TLS secure channel.**

New Relic stopped supporting TLS 1.0:
https://discuss.newrelic.com/t/january-tls-updates-apis-and-browser-apm/88869

This line should be added to the script before executing the API call:
[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11"

**Comment by nomansadiq11** [comment]
This is fixed and deployed the extension on live.

**Comment by noamgrinch** [comment]
Thanks!
